services:
  client:
    image: node:20
    command: >
      npx screepers-steamless-client
      --package /screeps.nw
      --host 0.0.0.0
    volumes:
      - ${SCREEPS_NW_PATH:?"SCREEPS_NW_PATH not set"}:/screeps.nw
    ports:
      - 8080:8080
    restart: unless-stopped
